=== Dabble-of-DevOps-Bio/ella/src/vardb/datamodel/jsonschemas/filterconfig.json
{
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/root.json",
    "type": "object",
    "required": ["name", "usergroup", "default", "filterconfig"],
    "properties": {
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "pattern": "^(.+)$"
        },
        "usergroup": {
            "$id": "#/properties/usergroup",
            "type": "string",
            "pattern": "^(.+)$"
        },
        "default": {
            "$id": "#/properties/default",
            "type": "boolean"
        },
        "filterconfig": {
            "$id": "#/properties/filterconfig",
            "type": "object",
            "required": ["filters"],
            "properties": {
                "filters": {
                    "$id": "#/properties/filterconfig/properties/filters",
                    "type": "array",
                    "items": {
                        "$id": "#/properties/filterconfig/properties/filters/items",
                        "type": "object",
                        "required": ["name", "config"],
                        "optional": ["exceptions"],
                        "properties": {
                            "name": {
                                "$id": "#/properties/filterconfig/properties/filters/items/properties/name",
                                "type": "string",
                                "pattern": "^(.*)$"
                            },
                            "config": {
                                "$id": "#/properties/filterconfig/properties/filters/items/properties/config",
                                "type": "object"
                            },
                            "exceptions": {
                                "$id": "#/properties/filterconfig/properties/filters/items/properties/exceptions",
                                "type": "array",
                                "items": {
                                    "$id": "#/properties/filterconfig/properties/filters/items/properties/exceptions/items",
                                    "type": "object",
                                    "required": ["name", "config"],
                                    "properties": {
                                        "name": {
                                            "$id": "#/properties/filterconfig/properties/filters/items/properties/exceptions/items/properties/name",
                                            "type": "string",
                                            "pattern": "^(.+)$"
                                        },
                                        "config": {
                                            "$id": "#/properties/filterconfig/properties/filters/items/properties/exceptions/items/properties/config",
                                            "type": "object"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== Dabble-of-DevOps-Bio/ella/src/vardb/testdata/filterconfigs.json
[
    {
        "name": "Default",
        "usergroup": "testgroup01",
        "default": true,
        "filterconfig": {
            "filters": [
                {
                    "name": "frequency",
                    "config": {},
                    "exclusions": [
                        {
                            "name": "classification",
                            "config": {}
                        }
                    ]
                },
                {
                    "name": "region",
                    "config": {},
                    "exclusions": [
                        {
                            "name": "classification",
                            "config": {}
                        }
                    ]
                }
            ]
        }
    },
    {
        "name": "FilterOverride",
        "usergroup": "testgroup02",
        "default": true,
        "filterconfig": {
            "filters": [
                {
                    "name": "frequency",
                    "config": {
                        "groups": {
                            "external": {
                                "GNOMAD_GENOMES": [
                                    "G",
                                    "AFR",
                                    "AMR",
                                    "EAS",
                                    "FIN",
                                    "NFE",
                                    "OTH",
                                    "SAS"
                                ],
                                "GNOMAD_EXOMES": [
                                    "G",
                                    "AFR",
                                    "AMR",
                                    "EAS",
                                    "FIN",
                                    "NFE",
                                    "OTH",
                                    "SAS"
                                ]
                            },
                            "internal": {
                                "inDB": ["OUSWES"]
                            }
                        },
                        "num_thresholds": {
                            "GNOMAD_GENOMES": {
                                "G": 5000,
                                "AFR": 5000,
                                "AMR": 5000,
                                "EAS": 5000,
                                "FIN": 5000,
                                "NFE": 5000,
                                "OTH": 5000,
                                "SAS": 5000
                            },
                            "GNOMAD_EXOMES": {
                                "G": 5000,
                                "AFR": 5000,
                                "AMR": 5000,
                                "EAS": 5000,
                                "FIN": 5000,
                                "NFE": 5000,
                                "OTH": 5000,
                                "SAS": 5000
                            }
                        },
                        "thresholds": {
                            "AD": {
                                "external": 0.005,
                                "internal": 0.05
                            },
                            "default": {
                                "external": 0.01,
                                "internal": 0.05
                            }
                        }
                    },
                    "exclusions": [
                        {
                            "name": "classification",
                            "config": {}
                        }
                    ]
                },
                {
                    "name": "region",
                    "config": {
                        "splice_region": [-20, 6],
                        "utr_region": [0, 0]
                    },
                    "exclusions": [
                        {
                            "name": "classification",
                            "config": {}
                        }
                    ]
                },
                {
                    "name": "quality",
                    "config": {
                        "qual": 100
                    },
                    "exclusions": [
                        {
                            "name": "classification",
                            "config": {}
                        }
                    ]
                },
                {
                    "name": "segregation",
                    "config": {},
                    "exclusions": [
                        {
                            "name": "classification",
                            "config": {}
                        }
                    ]
                }
            ]
        }
    }
]
